export const FETCH_FILMS = "COMMAND/FETCH_FILMS";
export const FILMS_RECEIVED = "EVENT/FILMS_RECEIVED";
export const FETCH_CHARACTERS = "COMMAND/FETCH_CHARACTERS";
export const CHARACTERS_RECEIVED = "EVENT/CHARACTERS_RECEIVED";